/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Child, ChildInterface } from "../Child";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract GrandChild",
        name: "_grandChild",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "childState",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "run",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b506040516102523803806102528339818101604052602081101561003357600080fd5b81019080805190602001909291905050508073ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff1660601b815250505060805160601c6101ba61009860003980608a52506101ba6000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80638cbd11031461003b578063c040622614610059575b600080fd5b610043610077565b6040518082815260200191505060405180910390f35b61006161007d565b6040518082815260200191505060405180910390f35b60005481565b60006115be6000819055507f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff1663c04062266040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156100f057600080fd5b505af1158015610104573d6000803e3d6000fd5b50505050600061017c576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260098152602001807f6661696c2068657265000000000000000000000000000000000000000000000081525060200191505060405180910390fd5b60005490509056fea26469706673582212205aeec51ccdfbacd310ac1fcc802652648665e102874a70b230c78ae61c06018964736f6c63430007030033";

export class Child__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _grandChild: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Child> {
    return super.deploy(_grandChild, overrides || {}) as Promise<Child>;
  }
  getDeployTransaction(
    _grandChild: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_grandChild, overrides || {});
  }
  attach(address: string): Child {
    return super.attach(address) as Child;
  }
  connect(signer: Signer): Child__factory {
    return super.connect(signer) as Child__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChildInterface {
    return new utils.Interface(_abi) as ChildInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Child {
    return new Contract(address, _abi, signerOrProvider) as Child;
  }
}
