/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Parent, ParentInterface } from "../Parent";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract Child",
        name: "_child",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "parentState",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "run",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b506040516102a83803806102a88339818101604052602081101561003357600080fd5b81019080805190602001909291905050508073ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff1660601b815250505060805160601c61021061009860003980607052506102106000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c04062261461003b578063f5ed1a5d14610045575b600080fd5b610043610063565b005b61004d6101d4565b6040518082815260200191505060405180910390f35b6115be60008190555060007f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff166040516024016040516020818303038152906040527fc0406226000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff83818316178352505050506040518082805190602001908083835b6020831061015b5780518252602082019150602081019050602083039250610138565b6001836020036101000a0380198251168184511680821785525050505050509050019150506000604051808303816000865af19150503d80600081146101bd576040519150601f19603f3d011682016040523d82523d6000602084013e6101c2565b606091505b5050905080156101d157600080fd5b50565b6000548156fea2646970667358221220d113ed6a68278523cdd54211f0a1c4339f84d22435750c2cdcee836059e0250c64736f6c63430007030033";

export class Parent__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Parent> {
    return super.deploy(_child, overrides || {}) as Promise<Parent>;
  }
  getDeployTransaction(
    _child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_child, overrides || {});
  }
  attach(address: string): Parent {
    return super.attach(address) as Parent;
  }
  connect(signer: Signer): Parent__factory {
    return super.connect(signer) as Parent__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ParentInterface {
    return new utils.Interface(_abi) as ParentInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Parent {
    return new Contract(address, _abi, signerOrProvider) as Parent;
  }
}
